name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run || true # prevents job failure so email always runs

      - name: Send result to Teams channel via Gmail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: "vignesh.listertechnologies@gmail.com"    # your Gmail ID
          password: "nvns simt juzt ospb" # Gmail App Password
          subject: "Cypress Pipeline - ${{ job.status }}"
          to: "e578a964.bounteous.com@amer.teams.ms"  # Teams channel email
          from: "GitHub Actions <${{ secrets.GMAIL_USERNAME }}>"
          body: |
            Repository: ${{ github.repository }}
            Workflow: ${{ github.workflow }}
            Run: ${{ github.run_number }}
            Status: ${{ job.status }}
            Logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
