name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run || true # prevents job failure so email always runs

      - name: Send result to Teams channel via Outlook
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 465
          secure: true
          username: "vignesh.listertechnologies@gmail.com"   # your Outlook email (e.g. kishore@yourorg.com)
          password: "nvns simt juzt ospb"   # your Outlook password
          subject: "Cypress Pipeline - ${{ job.status }}"
          to: "e578a964.bounteous.com@amer.teams.ms"
          from: "GitHub Actions vignesh.listertechnologies@gmail.com"
          body: |
            Repository: ${{ github.repository }}
            Workflow: ${{ github.workflow }}
            Run: ${{ github.run_number }}
            Status: ${{ job.status }}
            Logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}